-- LOCAL DISPOSABLE DATABASE ONLY. Minimal dependencies; no external services.
CREATE ROLE anon;
CREATE ROLE authenticated;
CREATE ROLE service_role;
CREATE TABLE auto_campaigns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint, staff_id bigint DEFAULT 1, organization_id bigint DEFAULT 1,
  name text, action_id text DEFAULT 'sms_send', status text DEFAULT 'chờ xử lý',
  is_delete boolean DEFAULT false, schedule timestamptz, original_schedule timestamptz,
  content text, extra_settings jsonb, images jsonb, note text, updated_at timestamptz
);
CREATE TABLE auto_campaign_input_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, campaign_id bigint, input_id bigint,
  status text DEFAULT 'chờ xử lý', is_delete boolean DEFAULT false, phone text,
  phone_carrier text, content text, name text, info1 text, info2 text, info3 text,
  info4 text, info5 text, schedule timestamptz, created_at timestamptz DEFAULT now(),
  date_action timestamptz, note text, uid text, email text,
  data_type_category_item_id bigint, auto_automation_detail_id bigint
);
CREATE TABLE auto_campaign_details (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, input_data_id bigint,
  campaign_id bigint, account_id bigint, action_code text, action_name text,
  status text, log text, data jsonb, counts_toward_limit boolean,
  is_delete boolean DEFAULT false, created_at timestamptz DEFAULT now(),
  auto_automation_detail_id bigint
);
CREATE TABLE test_counts(account_id bigint PRIMARY KEY, value integer NOT NULL);
CREATE FUNCTION increment_auto_account_action_count(bigint,text,integer) RETURNS void
LANGUAGE sql AS $$
  INSERT INTO test_counts VALUES ($1,$3)
  ON CONFLICT (account_id) DO UPDATE SET value=test_counts.value+EXCLUDED.value;
$$;
CREATE TABLE auto_automation (
  id bigint PRIMARY KEY, name text, source_campaign_id bigint,
  target_campaign_id bigint, target_data_group_id bigint,
  staff_id bigint, organization_id bigint, is_active boolean, is_delete boolean,
  activated_at timestamptz, automation_action_id text, data_type_code text,
  data_type_category_item_id bigint, config_version integer, schedule_mode text,
  fixed_at timestamptz
);
CREATE TABLE auto_automation_actions(id text PRIMARY KEY,is_available boolean,is_active boolean,is_delete boolean);
CREATE TABLE auto_automation_data_types(code text PRIMARY KEY,source_column text);
CREATE TABLE auto_campaign_action_data_types (
  campaign_action_id text,data_type_code text,can_source boolean,is_active boolean,
  is_delete boolean,data_type_category_item_id bigint,target_contact_type text
);
CREATE TABLE auto_account_contact_groups(id bigint PRIMARY KEY,staff_id bigint,organization_id bigint,purpose text,is_delete boolean);
CREATE TABLE auto_automation_trigger_statuses(automation_id bigint,status_value text,action_code text);
CREATE TABLE auto_automation_detail (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, automation_id bigint,
  parent_automation_detail_id bigint, source_campaign_detail_id bigint,
  source_campaign_input_data_id bigint,source_campaign_id bigint,source_account_id bigint,
  source_action_id text,source_action_code text,source_status text,target_campaign_id bigint,
  target_account_id bigint,target_action_id text,data_type_code text,data_value text,
  source_input_snapshot jsonb,config_snapshot jsonb,target_contact_group_id bigint,
  target_data_group_id bigint,scheduled_at timestamptz,status text,next_attempt_at timestamptz,
  last_error text,processed_at timestamptz,staff_id bigint,organization_id bigint,
  created_at timestamptz,updated_at timestamptz,
  UNIQUE(automation_id,source_campaign_detail_id)
);
CREATE TABLE auto_automation_enqueue_failures (
  source_campaign_detail_id bigint PRIMARY KEY,source_campaign_id bigint,source_status text,
  source_action_code text,source_is_delete boolean,event_at timestamptz,status text,
  next_attempt_at timestamptz,last_error text,resolved_at timestamptz,staff_id bigint,
  organization_id bigint,updated_at timestamptz
);
GRANT USAGE ON SCHEMA public TO service_role;
