CREATE TABLE IF NOT EXISTS public.aka_data_split_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id bigint NOT NULL REFERENCES public.org_organization(id),
  org_staff_id bigint NOT NULL REFERENCES public.org_staff(id),
  keywords text[] NOT NULL DEFAULT '{}'::text[],
  max_contact_in_day integer,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT aka_data_split_rules_org_staff_unique UNIQUE (organization_id, org_staff_id)
);

DROP TRIGGER IF EXISTS trg_aka_data_split_rules_updated_at ON public.aka_data_split_rules;
CREATE TRIGGER trg_aka_data_split_rules_updated_at
BEFORE UPDATE ON public.aka_data_split_rules
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

INSERT INTO public.aka_data_split_rules (
  organization_id,
  org_staff_id,
  keywords,
  max_contact_in_day,
  is_active
)
VALUES
  (1, 12, ARRAY['sms10','sms','zalo','zaloladi','zalo_fromfb','zalopmax','facebook','post','postnoti','postzalo','facebookpmax','webchat_zalo','webchat_sms','webchat_fb','webchat','fanpage','chatbot','zalopmax_2','zalobiz','zalo_download']::text[], 10, true),
  (1, 5, ARRAY['sms10','sms','zalo','zaloladi','zalo_fromfb','zalopmax','facebook','post','postnoti','postzalo','facebookpmax','webchat_zalo','webchat_sms','webchat_fb','webchat','fanpage','chatbot','zalopmax_2','zalobiz','zalo_download']::text[], 0, true),
  (1, 8, ARRAY['sms10','sms','zalo','zaloladi','zalo_fromfb','zalopmax','facebook','post','postnoti','postzalo','facebookpmax','webchat_zalo','webchat_sms','webchat_fb','webchat','fanpage','chatbot','zalopmax_2','zalobiz','zalo_download','data']::text[], 111, true),
  (1, 2, ARRAY['sms10','sms','zalo','zaloladi','zalo_fromfb','zalopmax','facebook','post','postnoti','postzalo','facebookpmax','webchat_zalo','webchat_sms','webchat_fb','webchat','fanpage','chatbot','zalopmax_2','zalobiz','zalo_download','map','chat']::text[], 111, true),
  (1, 23, ARRAY['sms10','sms','zalo','zaloladi','zalo_fromfb','zalopmax','facebook','post','postnoti','postzalo','facebookpmax','webchat_zalo','webchat_sms','webchat_fb','webchat','fanpage','chatbot','zalopmax_2','zalo_download','map','chat']::text[], 222, true),
  (1, 26, ARRAY['sms10','sms','zaloladi','zalo','zalopmax','zalo_fromfb','facebook','post','postnoti','postzalo','facebookpmax','webchat_zalo','webchat_sms','webchat_fb','webchat','fanpage','chatbot','zalopmax_2','zalobiz','zalo_download','map','chat']::text[], 111, true),
  (1, 7, ARRAY['sms10','sms','zalo','zaloladi','zalo_fromfb','zalopmax','facebook','post','postzalo','facebookpmax','webchat_zalo','webchat_sms','webchat_fb','webchat','fanpage','chatbot','zalopmax_2','zalo_download','hotline','map','chat']::text[], 111, true),
  (1, 6, ARRAY['sms10','sms','zalo','zaloladi','zalo_fromfb','zalopmax','facebook','post','postnoti','postzalo','facebookpmax','webchat_zalo','webchat_sms','webchat_fb','webchat','fanpage','chatbot','zalopmax_2','chat','zalobiz','zalo_download','hotline','map']::text[], 222, true)
ON CONFLICT (organization_id, org_staff_id) DO UPDATE
SET keywords = EXCLUDED.keywords,
    max_contact_in_day = EXCLUDED.max_contact_in_day,
    is_active = EXCLUDED.is_active,
    updated_at = now();

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'trg_aka_customer_split_create_crm'
  ) THEN
    EXECUTE 'ALTER TABLE public.aka_customer DISABLE TRIGGER trg_aka_customer_split_create_crm';
  END IF;
END $$;
