-- Shared media library for uploaded local files and cloud URLs.

BEGIN;

CREATE TABLE IF NOT EXISTS public.auto_media_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider text NOT NULL DEFAULT 'r2',
  original_name text NOT NULL,
  local_path text,
  cloud_url text NOT NULL,
  object_key text,
  mime_type text,
  size_bytes bigint,
  is_delete boolean NOT NULL DEFAULT false,
  staff_id bigint NOT NULL REFERENCES public.org_staff(id) ON DELETE CASCADE,
  organization_id bigint REFERENCES public.org_organization(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_auto_media_files_staff
  ON public.auto_media_files (staff_id, is_delete, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_auto_media_files_provider
  ON public.auto_media_files (provider, is_delete);

INSERT INTO public.auto_system_settings (key, value, description, is_secret, is_active)
VALUES
  ('media.storage.provider', 'r2', 'Cloud media storage provider.', false, true),
  ('media.storage.endpoint_url', '', 'S3-compatible endpoint URL for media uploads.', false, true),
  ('media.storage.access_key_id', '', 'Access key ID for media uploads.', false, true),
  ('media.storage.secret_access_key', '', 'Secret access key for media uploads.', true, true),
  ('media.storage.bucket', '', 'Bucket name for media uploads.', false, true),
  ('media.storage.public_base_url', '', 'Public base URL used to build uploaded media links.', false, true),
  ('media.storage.key_prefix', '', 'Optional key prefix for uploaded media objects.', false, true)
ON CONFLICT (key) DO NOTHING;

COMMENT ON TABLE public.auto_media_files IS
  'Staff-scoped media file library with local paths and cloud URLs.';

COMMENT ON COLUMN public.auto_media_files.object_key IS
  'Provider object key inside the cloud bucket; campaign snapshots should not depend on this value.';

NOTIFY pgrst, 'reload schema';

COMMIT;
