-- Shared category catalog and one stable displayed source per Data Group member.
--
-- Provenance remains additive: a membership may keep many current origins.  The
-- primary pointer is only the source displayed by list APIs.  Once selected it
-- remains stable while that exact origin is current and its shared category is
-- active.  A retired source falls back to the oldest remaining current mapped
-- origin, so a later duplicate observation never silently changes the label.

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Cross-project category catalog.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.category_type (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  namespace text NOT NULL DEFAULT 'common',
  code text NOT NULL,
  name text NOT NULL,
  managed_by text NOT NULL DEFAULT 'system',
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT category_type_namespace_check CHECK (
    namespace = lower(btrim(namespace))
    AND namespace ~ '^[a-z][a-z0-9_.-]{0,127}$'
  ),
  CONSTRAINT category_type_code_check CHECK (
    code = lower(btrim(code))
    AND code ~ '^[a-z][a-z0-9_.-]{0,127}$'
  ),
  CONSTRAINT category_type_name_check CHECK (
    length(btrim(name)) BETWEEN 1 AND 255
  ),
  CONSTRAINT category_type_managed_by_check CHECK (
    managed_by IN ('manual', 'sql_server_sync', 'system')
  ),
  CONSTRAINT uq_category_type_namespace_code UNIQUE (namespace, code)
);

CREATE TABLE IF NOT EXISTS public.category_item (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_type_id bigint NOT NULL
    REFERENCES public.category_type(id) ON DELETE RESTRICT,
  code text NOT NULL,
  name text NOT NULL,
  managed_by text NOT NULL DEFAULT 'system',
  description text,
  sort_order integer NOT NULL DEFAULT 0,
  color text,
  external_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT category_item_code_check CHECK (
    code = lower(btrim(code))
    AND code ~ '^[a-z][a-z0-9_.-]{0,127}$'
  ),
  CONSTRAINT category_item_name_check CHECK (
    length(btrim(name)) BETWEEN 1 AND 255
  ),
  CONSTRAINT category_item_managed_by_check CHECK (
    managed_by IN ('manual', 'sql_server_sync', 'system')
  ),
  CONSTRAINT category_item_color_check CHECK (
    color IS NULL OR color ~ '^#[0-9A-Fa-f]{6}([0-9A-Fa-f]{2})?$'
  ),
  CONSTRAINT category_item_metadata_check CHECK (
    jsonb_typeof(metadata) = 'object'
  ),
  CONSTRAINT category_item_sort_order_check CHECK (sort_order >= 0),
  CONSTRAINT uq_category_item_type_code UNIQUE (category_type_id, code),
  CONSTRAINT uq_category_item_type_external_id UNIQUE (category_type_id, external_id)
);

CREATE INDEX IF NOT EXISTS idx_category_item_active_type_sort
  ON public.category_item (category_type_id, sort_order, id)
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_category_type_active_namespace
  ON public.category_type (namespace, code, id)
  WHERE is_active = true;

CREATE OR REPLACE FUNCTION public.touch_category_catalog_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  NEW.updated_at := clock_timestamp();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_category_type_updated_at
  ON public.category_type;
CREATE TRIGGER trg_touch_category_type_updated_at
BEFORE UPDATE ON public.category_type
FOR EACH ROW
EXECUTE FUNCTION public.touch_category_catalog_updated_at();

DROP TRIGGER IF EXISTS trg_touch_category_item_updated_at
  ON public.category_item;
CREATE TRIGGER trg_touch_category_item_updated_at
BEFORE UPDATE ON public.category_item
FOR EACH ROW
EXECUTE FUNCTION public.touch_category_catalog_updated_at();

INSERT INTO public.category_type (
  namespace,
  code,
  name,
  managed_by,
  description,
  is_active
)
VALUES (
  'common',
  'data_source',
  'Nguồn data',
  'system',
  'Nguồn tạo ra một bản ghi dữ liệu, dùng chung giữa các sản phẩm.',
  true
)
ON CONFLICT (namespace, code) DO UPDATE SET
  name = EXCLUDED.name,
  managed_by = EXCLUDED.managed_by,
  description = EXCLUDED.description,
  is_active = true;

WITH data_source_type AS (
  SELECT category_type.id
  FROM public.category_type
  WHERE category_type.namespace = 'common'
    AND category_type.code = 'data_source'
    AND category_type.managed_by = 'system'
)
INSERT INTO public.category_item (
  category_type_id,
  code,
  name,
  managed_by,
  description,
  sort_order,
  color,
  external_id,
  metadata,
  is_active
)
SELECT
  data_source_type.id,
  seed.code,
  seed.name,
  'system',
  seed.description,
  seed.sort_order,
  NULL,
  seed.code,
  seed.metadata,
  true
FROM data_source_type
CROSS JOIN (VALUES
  (
    'upload'::text,
    'Upload data'::text,
    'Dữ liệu được thêm thủ công hoặc tải lên.'::text,
    10,
    '{"originKinds":["manual","upload"]}'::jsonb
  ),
  (
    'scan'::text,
    'Quét data'::text,
    'Dữ liệu được quét từ một tài khoản hoặc nguồn liên kết.'::text,
    20,
    '{"originKinds":["scan"]}'::jsonb
  ),
  (
    'automation'::text,
    'Tự động hóa'::text,
    'Dữ liệu được đưa vào bởi một quy tắc tự động hóa.'::text,
    30,
    '{"originKinds":["automation"]}'::jsonb
  )
) AS seed(code, name, description, sort_order, metadata)
ON CONFLICT (category_type_id, code) DO UPDATE SET
  name = EXCLUDED.name,
  managed_by = EXCLUDED.managed_by,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  color = EXCLUDED.color,
  external_id = EXCLUDED.external_id,
  metadata = EXCLUDED.metadata,
  is_active = true;

-- A system-managed type has exactly the three active system values defined by
-- this release.  Retain unknown historical rows for referential audit, but do
-- not let them become selectable categories.
UPDATE public.category_item AS category_item
SET is_active = false
FROM public.category_type AS category_type
WHERE category_type.id = category_item.category_type_id
  AND category_type.namespace = 'common'
  AND category_type.code = 'data_source'
  AND category_type.managed_by = 'system'
  AND category_item.managed_by = 'system'
  AND category_item.code NOT IN ('upload', 'scan', 'automation')
  AND category_item.is_active = true;

-- ---------------------------------------------------------------------------
-- 2. Durable category per origin and one exact primary origin per member.
-- ---------------------------------------------------------------------------

ALTER TABLE public.auto_account_contact_group_member_origins
  ADD COLUMN IF NOT EXISTS source_category_item_id bigint;

ALTER TABLE public.auto_account_contact_group_members
  ADD COLUMN IF NOT EXISTS primary_origin_id bigint;

DO $data_group_primary_source_constraints$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_catalog.pg_constraint
    WHERE conrelid = 'public.auto_account_contact_group_member_origins'::regclass
      AND conname = 'auto_account_contact_group_member_origins_source_category_item_fkey'
  ) THEN
    ALTER TABLE public.auto_account_contact_group_member_origins
      ADD CONSTRAINT auto_account_contact_group_member_origins_source_category_item_fkey
      FOREIGN KEY (source_category_item_id)
      REFERENCES public.category_item(id)
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_catalog.pg_constraint
    WHERE conrelid = 'public.auto_account_contact_group_members'::regclass
      AND conname = 'auto_account_contact_group_members_primary_origin_fkey'
  ) THEN
    ALTER TABLE public.auto_account_contact_group_members
      ADD CONSTRAINT auto_account_contact_group_members_primary_origin_fkey
      FOREIGN KEY (primary_origin_id)
      REFERENCES public.auto_account_contact_group_member_origins(id)
      ON DELETE SET NULL
      DEFERRABLE INITIALLY IMMEDIATE;
  END IF;
END;
$data_group_primary_source_constraints$;

CREATE INDEX IF NOT EXISTS idx_data_group_member_origins_source_category
  ON public.auto_account_contact_group_member_origins (
    source_category_item_id,
    membership_id,
    created_at,
    id
  )
  WHERE is_current = true AND source_category_item_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_data_group_members_primary_origin
  ON public.auto_account_contact_group_members (primary_origin_id)
  WHERE primary_origin_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.aka_agent_data_group_source_code(
  p_origin_kind text
)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
SET search_path = pg_catalog, public
AS $$
  SELECT CASE lower(btrim(COALESCE(p_origin_kind, '')))
    WHEN 'manual' THEN 'upload'
    WHEN 'upload' THEN 'upload'
    WHEN 'scan' THEN 'scan'
    WHEN 'automation' THEN 'automation'
    ELSE NULL
  END;
$$;

CREATE OR REPLACE FUNCTION public.aka_agent_data_group_source_category_item_id(
  p_origin_kind text
)
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT category_item.id
  FROM public.category_type AS category_type
  JOIN public.category_item AS category_item
    ON category_item.category_type_id = category_type.id
  WHERE category_type.namespace = 'common'
    AND category_type.code = 'data_source'
    AND category_type.managed_by = 'system'
    AND category_item.managed_by = 'system'
    AND category_item.code = public.aka_agent_data_group_source_code(p_origin_kind)
  ORDER BY category_item.id
  LIMIT 1;
$$;

-- Existing precise provenance is classified without guessing.  API and both
-- legacy kinds deliberately remain NULL even if their display snapshots look
-- like an upload.
UPDATE public.auto_account_contact_group_member_origins AS origin
SET source_category_item_id =
      public.aka_agent_data_group_source_category_item_id(origin.kind),
    updated_at = clock_timestamp()
WHERE EXISTS (
    SELECT 1
    FROM public.auto_account_contact_group_members AS member
    JOIN public.auto_account_contact_groups AS contact_group
      ON contact_group.id = member.group_id
     AND contact_group.purpose = 'data_group'
    WHERE member.id = origin.membership_id
  )
  AND origin.source_category_item_id IS DISTINCT FROM
      public.aka_agent_data_group_source_category_item_id(origin.kind);

UPDATE public.auto_account_contact_group_member_origins AS origin
SET source_category_item_id = NULL,
    updated_at = clock_timestamp()
WHERE origin.source_category_item_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.auto_account_contact_group_members AS member
    JOIN public.auto_account_contact_groups AS contact_group
      ON contact_group.id = member.group_id
     AND contact_group.purpose = 'data_group'
    WHERE member.id = origin.membership_id
  );

-- Keep an already-valid sticky primary on rerun. Clear only inactive/invalid
-- pointers, then deterministically fill missing values old-first.
UPDATE public.auto_account_contact_group_members AS member
SET primary_origin_id = NULL
WHERE member.primary_origin_id IS NOT NULL
  AND (
    member.is_delete = true
    OR NOT EXISTS (
      SELECT 1
      FROM public.auto_account_contact_groups AS contact_group
      WHERE contact_group.id = member.group_id
        AND contact_group.purpose = 'data_group'
    )
    OR NOT EXISTS (
      SELECT 1
      FROM public.auto_account_contact_group_member_origins AS origin
      JOIN public.category_item AS category_item
        ON category_item.id = origin.source_category_item_id
       AND category_item.is_active = true
       AND category_item.managed_by = 'system'
       AND category_item.code = public.aka_agent_data_group_source_code(origin.kind)
      JOIN public.category_type AS category_type
        ON category_type.id = category_item.category_type_id
       AND category_type.namespace = 'common'
       AND category_type.code = 'data_source'
       AND category_type.managed_by = 'system'
       AND category_type.is_active = true
      WHERE origin.id = member.primary_origin_id
        AND origin.membership_id = member.id
        AND origin.is_current = true
    )
  );

WITH ranked_primary AS (
  SELECT
    origin.membership_id,
    origin.id,
    row_number() OVER (
      PARTITION BY origin.membership_id
      ORDER BY origin.created_at, origin.id
    ) AS source_rank
  FROM public.auto_account_contact_group_member_origins AS origin
  JOIN public.auto_account_contact_group_members AS member
    ON member.id = origin.membership_id
   AND member.is_delete = false
  JOIN public.auto_account_contact_groups AS contact_group
    ON contact_group.id = member.group_id
   AND contact_group.purpose = 'data_group'
  JOIN public.category_item AS category_item
    ON category_item.id = origin.source_category_item_id
   AND category_item.is_active = true
   AND category_item.managed_by = 'system'
   AND category_item.code = public.aka_agent_data_group_source_code(origin.kind)
  JOIN public.category_type AS category_type
    ON category_type.id = category_item.category_type_id
   AND category_type.namespace = 'common'
   AND category_type.code = 'data_source'
   AND category_type.managed_by = 'system'
   AND category_type.is_active = true
  WHERE origin.is_current = true
)
UPDATE public.auto_account_contact_group_members AS member
SET primary_origin_id = ranked_primary.id
FROM ranked_primary
WHERE ranked_primary.membership_id = member.id
  AND ranked_primary.source_rank = 1
  AND member.primary_origin_id IS NULL;

CREATE OR REPLACE FUNCTION public.aka_agent_sync_data_group_member_primary_origin(
  p_membership_id bigint,
  p_preferred_origin_id bigint DEFAULT NULL,
  p_force_preferred boolean DEFAULT false
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_member public.auto_account_contact_group_members%ROWTYPE;
  v_primary_origin_id bigint;
BEGIN
  SELECT member.*
  INTO v_member
  FROM public.auto_account_contact_group_members AS member
  JOIN public.auto_account_contact_groups AS contact_group
    ON contact_group.id = member.group_id
   AND contact_group.purpose = 'data_group'
  WHERE member.id = p_membership_id
  FOR UPDATE OF member;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  IF v_member.is_delete THEN
    IF v_member.primary_origin_id IS NOT NULL THEN
      UPDATE public.auto_account_contact_group_members
      SET primary_origin_id = NULL
      WHERE id = v_member.id;
    END IF;
    RETURN;
  END IF;

  -- A valid current primary is sticky.  This is the key distinction between
  -- provenance (many current rows) and the one source displayed in the UI.
  IF NOT COALESCE(p_force_preferred, false)
    AND v_member.primary_origin_id IS NOT NULL
    AND EXISTS (
      SELECT 1
      FROM public.auto_account_contact_group_member_origins AS origin
      JOIN public.category_item AS category_item
        ON category_item.id = origin.source_category_item_id
       AND category_item.is_active = true
       AND category_item.managed_by = 'system'
       AND category_item.code = public.aka_agent_data_group_source_code(origin.kind)
      JOIN public.category_type AS category_type
        ON category_type.id = category_item.category_type_id
       AND category_type.namespace = 'common'
       AND category_type.code = 'data_source'
       AND category_type.managed_by = 'system'
       AND category_type.is_active = true
      WHERE origin.id = v_member.primary_origin_id
        AND origin.membership_id = v_member.id
        AND origin.is_current = true
    )
  THEN
    RETURN;
  END IF;

  IF p_preferred_origin_id IS NOT NULL THEN
    SELECT origin.id
    INTO v_primary_origin_id
    FROM public.auto_account_contact_group_member_origins AS origin
    JOIN public.category_item AS category_item
      ON category_item.id = origin.source_category_item_id
     AND category_item.is_active = true
     AND category_item.managed_by = 'system'
     AND category_item.code = public.aka_agent_data_group_source_code(origin.kind)
    JOIN public.category_type AS category_type
      ON category_type.id = category_item.category_type_id
     AND category_type.namespace = 'common'
     AND category_type.code = 'data_source'
     AND category_type.managed_by = 'system'
     AND category_type.is_active = true
    WHERE origin.id = p_preferred_origin_id
      AND origin.membership_id = v_member.id
      AND origin.is_current = true;
  END IF;

  IF v_primary_origin_id IS NULL THEN
    SELECT origin.id
    INTO v_primary_origin_id
    FROM public.auto_account_contact_group_member_origins AS origin
    JOIN public.category_item AS category_item
      ON category_item.id = origin.source_category_item_id
     AND category_item.is_active = true
     AND category_item.managed_by = 'system'
     AND category_item.code = public.aka_agent_data_group_source_code(origin.kind)
    JOIN public.category_type AS category_type
      ON category_type.id = category_item.category_type_id
     AND category_type.namespace = 'common'
     AND category_type.code = 'data_source'
     AND category_type.managed_by = 'system'
     AND category_type.is_active = true
    WHERE origin.membership_id = v_member.id
      AND origin.is_current = true
    ORDER BY origin.created_at, origin.id
    LIMIT 1;
  END IF;

  UPDATE public.auto_account_contact_group_members
  SET primary_origin_id = v_primary_origin_id
  WHERE id = v_member.id
    AND primary_origin_id IS DISTINCT FROM v_primary_origin_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.aka_agent_stamp_data_group_source_category()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.auto_account_contact_group_members AS member
    JOIN public.auto_account_contact_groups AS contact_group
      ON contact_group.id = member.group_id
     AND contact_group.purpose = 'data_group'
    WHERE member.id = NEW.membership_id
  ) THEN
    NEW.source_category_item_id :=
      public.aka_agent_data_group_source_category_item_id(NEW.kind);
  ELSE
    NEW.source_category_item_id := NULL;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_aka_agent_stamp_data_group_source_category
  ON public.auto_account_contact_group_member_origins;
CREATE TRIGGER trg_aka_agent_stamp_data_group_source_category
BEFORE INSERT OR UPDATE OF membership_id, kind, source_category_item_id
ON public.auto_account_contact_group_member_origins
FOR EACH ROW
EXECUTE FUNCTION public.aka_agent_stamp_data_group_source_category();

CREATE OR REPLACE FUNCTION public.aka_agent_refresh_data_group_primary_from_origin()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  -- A new/reactivated membership deliberately has no primary. Its first
  -- current mapped origin becomes the source of that activation. Existing
  -- memberships keep their non-NULL pointer here; retirement is repaired by
  -- the deferred trigger below using the transaction's final origin state.
  IF NEW.is_current
    AND NEW.source_category_item_id IS NOT NULL
    AND EXISTS (
      SELECT 1
      FROM public.auto_account_contact_group_members AS member
      WHERE member.id = NEW.membership_id
        AND member.primary_origin_id IS NULL
        AND member.is_delete = false
    )
  THEN
    PERFORM public.aka_agent_sync_data_group_member_primary_origin(
      NEW.membership_id,
      NEW.id
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_aka_agent_refresh_data_group_primary_from_origin
  ON public.auto_account_contact_group_member_origins;
CREATE TRIGGER trg_aka_agent_refresh_data_group_primary_from_origin
AFTER INSERT OR UPDATE OF
  membership_id,
  kind,
  source_category_item_id,
  is_current
ON public.auto_account_contact_group_member_origins
FOR EACH ROW
EXECUTE FUNCTION public.aka_agent_refresh_data_group_primary_from_origin();

CREATE OR REPLACE FUNCTION public.aka_agent_repair_data_group_primary_from_origin()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_replacement_origin_id bigint;
BEGIN
  IF TG_OP = 'DELETE' THEN
    PERFORM public.aka_agent_sync_data_group_member_primary_origin(
      OLD.membership_id
    );
    RETURN OLD;
  END IF;

  IF OLD.membership_id IS DISTINCT FROM NEW.membership_id
    AND EXISTS (
      SELECT 1
      FROM public.auto_account_contact_group_members AS member
      WHERE member.id = OLD.membership_id
        AND member.primary_origin_id = NEW.id
    )
  THEN
    PERFORM public.aka_agent_sync_data_group_member_primary_origin(
      OLD.membership_id
    );
  END IF;

  IF (
      OLD.membership_id IS DISTINCT FROM NEW.membership_id
      OR (OLD.is_current AND NOT NEW.is_current)
      OR OLD.kind IS DISTINCT FROM NEW.kind
      OR OLD.source_category_item_id IS DISTINCT FROM NEW.source_category_item_id
    )
    AND EXISTS (
      SELECT 1
      FROM public.auto_account_contact_group_members AS member
      WHERE member.id = NEW.membership_id
        AND member.primary_origin_id = NEW.id
  )
  THEN
    -- Dataset refresh can replace an origin identity (for example after a
    -- dataset rename or relationship change). If the retired origin was the
    -- displayed primary, transfer that primary to the final current origin of
    -- the same dataset. A genuine removal has no such replacement and falls
    -- back to the oldest other current mapped origin.
    IF OLD.is_current
      AND NOT NEW.is_current
      AND OLD.dataset_id IS NOT NULL
    THEN
      SELECT origin.id
      INTO v_replacement_origin_id
      FROM public.auto_account_contact_group_member_origins AS origin
      JOIN public.category_item AS category_item
        ON category_item.id = origin.source_category_item_id
       AND category_item.is_active = true
       AND category_item.managed_by = 'system'
       AND category_item.code = public.aka_agent_data_group_source_code(origin.kind)
      JOIN public.category_type AS category_type
        ON category_type.id = category_item.category_type_id
       AND category_type.namespace = 'common'
       AND category_type.code = 'data_source'
       AND category_type.managed_by = 'system'
       AND category_type.is_active = true
      WHERE origin.membership_id = NEW.membership_id
        AND origin.dataset_id = OLD.dataset_id
        AND origin.is_current = true
      ORDER BY
        (origin.id = NEW.id) DESC,
        origin.updated_at DESC,
        origin.created_at DESC,
        origin.id DESC
      LIMIT 1;
    END IF;

    PERFORM public.aka_agent_sync_data_group_member_primary_origin(
      NEW.membership_id,
      v_replacement_origin_id,
      v_replacement_origin_id IS NOT NULL
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_aka_agent_deferred_repair_data_group_primary_from_origin
  ON public.auto_account_contact_group_member_origins;
CREATE CONSTRAINT TRIGGER trg_aka_agent_deferred_repair_data_group_primary_from_origin
AFTER UPDATE OR DELETE
ON public.auto_account_contact_group_member_origins
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION public.aka_agent_repair_data_group_primary_from_origin();

CREATE OR REPLACE FUNCTION public.aka_agent_guard_data_group_member_primary_origin()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM public.auto_account_contact_groups AS contact_group
    WHERE contact_group.id = NEW.group_id
      AND contact_group.purpose = 'data_group'
  ) THEN
    NEW.primary_origin_id := NULL;
    RETURN NEW;
  END IF;

  IF NEW.is_delete THEN
    NEW.primary_origin_id := NULL;
    RETURN NEW;
  END IF;

  IF NEW.primary_origin_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.auto_account_contact_group_member_origins AS origin
    JOIN public.category_item AS category_item
      ON category_item.id = origin.source_category_item_id
     AND category_item.is_active = true
     AND category_item.managed_by = 'system'
     AND category_item.code = public.aka_agent_data_group_source_code(origin.kind)
    JOIN public.category_type AS category_type
      ON category_type.id = category_item.category_type_id
     AND category_type.namespace = 'common'
     AND category_type.code = 'data_source'
     AND category_type.managed_by = 'system'
     AND category_type.is_active = true
    WHERE origin.id = NEW.primary_origin_id
      AND origin.membership_id = NEW.id
      AND origin.is_current = true
  ) THEN
    RAISE EXCEPTION 'invalid_data_group_member_primary_origin';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_aka_agent_guard_data_group_member_primary_origin
  ON public.auto_account_contact_group_members;
CREATE TRIGGER trg_aka_agent_guard_data_group_member_primary_origin
BEFORE INSERT OR UPDATE OF primary_origin_id, is_delete
ON public.auto_account_contact_group_members
FOR EACH ROW
EXECUTE FUNCTION public.aka_agent_guard_data_group_member_primary_origin();

CREATE OR REPLACE FUNCTION public.aka_agent_refresh_data_group_primary_from_member()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  -- Insert/reactivation deliberately waits for the origin writer. The first
  -- current mapped origin observed after activation is the source of that
  -- activation, even when older historical origins are still current.
  IF NEW.is_delete THEN
    PERFORM public.aka_agent_sync_data_group_member_primary_origin(NEW.id);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_aka_agent_refresh_data_group_primary_from_member
  ON public.auto_account_contact_group_members;
CREATE TRIGGER trg_aka_agent_refresh_data_group_primary_from_member
AFTER UPDATE OF is_delete
ON public.auto_account_contact_group_members
FOR EACH ROW
EXECUTE FUNCTION public.aka_agent_refresh_data_group_primary_from_member();

-- Retiring an active shared catalog value invalidates only members currently
-- displaying it. Reactivation does not steal primary from a valid fallback.
CREATE OR REPLACE FUNCTION public.aka_agent_refresh_data_group_primary_from_category_item()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_membership_id bigint;
BEGIN
  FOR v_membership_id IN
    SELECT DISTINCT origin.membership_id
    FROM public.auto_account_contact_group_member_origins AS origin
    WHERE origin.source_category_item_id IN (OLD.id, NEW.id)
    ORDER BY origin.membership_id
  LOOP
    PERFORM public.aka_agent_sync_data_group_member_primary_origin(v_membership_id);
  END LOOP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_aka_agent_refresh_data_group_primary_from_category_item
  ON public.category_item;
CREATE TRIGGER trg_aka_agent_refresh_data_group_primary_from_category_item
AFTER UPDATE OF category_type_id, code, managed_by, is_active
ON public.category_item
FOR EACH ROW
WHEN (
  OLD.category_type_id IS DISTINCT FROM NEW.category_type_id
  OR OLD.code IS DISTINCT FROM NEW.code
  OR OLD.managed_by IS DISTINCT FROM NEW.managed_by
  OR OLD.is_active IS DISTINCT FROM NEW.is_active
)
EXECUTE FUNCTION public.aka_agent_refresh_data_group_primary_from_category_item();

CREATE OR REPLACE FUNCTION public.aka_agent_refresh_data_group_primary_from_category_type()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_membership_id bigint;
BEGIN
  FOR v_membership_id IN
    SELECT DISTINCT origin.membership_id
    FROM public.auto_account_contact_group_member_origins AS origin
    JOIN public.category_item AS category_item
      ON category_item.id = origin.source_category_item_id
    WHERE category_item.category_type_id IN (OLD.id, NEW.id)
    ORDER BY origin.membership_id
  LOOP
    PERFORM public.aka_agent_sync_data_group_member_primary_origin(v_membership_id);
  END LOOP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_aka_agent_refresh_data_group_primary_from_category_type
  ON public.category_type;
CREATE TRIGGER trg_aka_agent_refresh_data_group_primary_from_category_type
AFTER UPDATE OF namespace, code, managed_by, is_active
ON public.category_type
FOR EACH ROW
WHEN (
  OLD.namespace IS DISTINCT FROM NEW.namespace
  OR OLD.code IS DISTINCT FROM NEW.code
  OR OLD.managed_by IS DISTINCT FROM NEW.managed_by
  OR OLD.is_active IS DISTINCT FROM NEW.is_active
)
EXECUTE FUNCTION public.aka_agent_refresh_data_group_primary_from_category_type();

-- ---------------------------------------------------------------------------
-- 3. Preserve source primary through duplicate/move transport.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.aka_agent_sync_copied_data_group_origins(
  p_source_membership_id bigint,
  p_target_membership_id bigint,
  p_force_source_primary boolean DEFAULT false
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_preferred_origin_id bigint;
BEGIN
  IF p_source_membership_id IS NULL
    OR p_target_membership_id IS NULL
    OR p_source_membership_id = p_target_membership_id
    OR NOT EXISTS (
      SELECT 1
      FROM public.auto_account_contact_group_members AS source_member
      JOIN public.auto_account_contact_group_members AS target_member
        ON target_member.id = p_target_membership_id
       AND target_member.contact_id = source_member.contact_id
      JOIN public.auto_account_contact_groups AS source_group
        ON source_group.id = source_member.group_id
       AND source_group.purpose = 'data_group'
      JOIN public.auto_account_contact_groups AS target_group
        ON target_group.id = target_member.group_id
       AND target_group.purpose = 'data_group'
       AND target_group.staff_id IS NOT DISTINCT FROM source_group.staff_id
       AND target_group.organization_id IS NOT DISTINCT FROM source_group.organization_id
      WHERE source_member.id = p_source_membership_id
        AND source_member.is_delete = false
        AND target_member.is_delete = false
    )
  THEN
    RAISE EXCEPTION 'invalid_data_group_origin_copy';
  END IF;

  -- ON CONFLICT DO NOTHING in the v186 move writer can meet a historical
  -- inactive identity. Reactivate every exact origin which is current on the
  -- source; this keeps provenance and primary selection in agreement.
  UPDATE public.auto_account_contact_group_member_origins AS target_origin
  SET is_current = true,
      updated_at = clock_timestamp()
  FROM public.auto_account_contact_group_member_origins AS source_origin
  WHERE source_origin.membership_id = p_source_membership_id
    AND source_origin.is_current = true
    AND target_origin.membership_id = p_target_membership_id
    AND target_origin.kind = source_origin.kind
    AND target_origin.dataset_id IS NOT DISTINCT FROM source_origin.dataset_id
    AND target_origin.batch_id IS NOT DISTINCT FROM source_origin.batch_id
    AND target_origin.source_account_id IS NOT DISTINCT FROM source_origin.source_account_id
    AND target_origin.automation_detail_id IS NOT DISTINCT FROM source_origin.automation_detail_id
    AND target_origin.source_name_snapshot IS NOT DISTINCT FROM source_origin.source_name_snapshot
    AND target_origin.relationship_kind IS NOT DISTINCT FROM source_origin.relationship_kind
    AND target_origin.is_current = false;

  SELECT target_origin.id
  INTO v_preferred_origin_id
  FROM public.auto_account_contact_group_members AS source_member
  JOIN public.auto_account_contact_group_member_origins AS source_origin
    ON source_origin.id = source_member.primary_origin_id
   AND source_origin.membership_id = source_member.id
   AND source_origin.is_current = true
  JOIN public.auto_account_contact_group_member_origins AS target_origin
    ON target_origin.membership_id = p_target_membership_id
   AND target_origin.kind = source_origin.kind
   AND target_origin.dataset_id IS NOT DISTINCT FROM source_origin.dataset_id
   AND target_origin.batch_id IS NOT DISTINCT FROM source_origin.batch_id
   AND target_origin.source_account_id IS NOT DISTINCT FROM source_origin.source_account_id
   AND target_origin.automation_detail_id IS NOT DISTINCT FROM source_origin.automation_detail_id
   AND target_origin.source_name_snapshot IS NOT DISTINCT FROM source_origin.source_name_snapshot
   AND target_origin.relationship_kind IS NOT DISTINCT FROM source_origin.relationship_kind
   AND target_origin.is_current = true
  WHERE source_member.id = p_source_membership_id
  ORDER BY target_origin.created_at, target_origin.id
  LIMIT 1;

  PERFORM public.aka_agent_sync_data_group_member_primary_origin(
    p_target_membership_id,
    v_preferred_origin_id,
    COALESCE(p_force_source_primary, false) AND v_preferred_origin_id IS NOT NULL
  );
END;
$$;

-- Patch the two live v186 writers instead of maintaining forked copies of
-- their large RPC bodies. Exact occurrence assertions make schema drift fail
-- closed. v193 already patched both SELECT lists to copy relationship_kind.
DO $patch_duplicate_primary_source$
DECLARE
  v_signature regprocedure := pg_catalog.to_regprocedure(
    'public.aka_agent_duplicate_data_group(bigint,bigint,bigint,text,text)'
  );
  v_definition text;
  v_old text := $old$
  WHERE source_member.group_id = v_source.id AND source_member.is_delete = false
  ON CONFLICT DO NOTHING;

  IF v_batch.id IS NOT NULL THEN
$old$;
  v_new text := $new$
  WHERE source_member.group_id = v_source.id AND source_member.is_delete = false
  ON CONFLICT DO NOTHING;

  PERFORM public.aka_agent_sync_copied_data_group_origins(
    source_member.id,
    target_member.id,
    true
  )
  FROM public.auto_account_contact_group_members AS source_member
  JOIN public.auto_account_contact_group_members AS target_member
    ON target_member.group_id = v_target.id
   AND target_member.contact_id = source_member.contact_id
  WHERE source_member.group_id = v_source.id
    AND source_member.is_delete = false
  ORDER BY source_member.id;

  IF v_batch.id IS NOT NULL THEN
$new$;
BEGIN
  IF v_signature IS NULL THEN
    RAISE EXCEPTION 'missing_data_group_duplicate_writer';
  END IF;

  SELECT pg_catalog.pg_get_functiondef(v_signature)
  INTO v_definition;

  IF pg_catalog.strpos(v_definition, 'aka_agent_sync_copied_data_group_origins') > 0 THEN
    RETURN;
  END IF;
  IF (
    pg_catalog.length(v_definition)
    - pg_catalog.length(pg_catalog.replace(v_definition, v_old, ''))
  ) <> pg_catalog.length(v_old) THEN
    RAISE EXCEPTION 'unexpected_data_group_duplicate_origin_shape';
  END IF;

  EXECUTE pg_catalog.replace(v_definition, v_old, v_new);
END;
$patch_duplicate_primary_source$;

DO $patch_move_primary_source$
DECLARE
  v_signature regprocedure := pg_catalog.to_regprocedure(
    'public.aka_agent_move_data_group_members(bigint,bigint,text,bigint,bigint[],bigint)'
  );
  v_definition text;
  v_old_declaration text := $old$
  v_target_member public.auto_account_contact_group_members%ROWTYPE;
  v_bound_source record;
$old$;
  v_new_declaration text := $new$
  v_target_member public.auto_account_contact_group_members%ROWTYPE;
  v_target_primary_before bigint;
  v_bound_source record;
$new$;
  v_old_upsert text := $old$
    LOOP
      INSERT INTO public.auto_account_contact_group_members AS existing_member (
$old$;
  v_new_upsert text := $new$
    LOOP
      SELECT member.primary_origin_id
      INTO v_target_primary_before
      FROM public.auto_account_contact_group_members AS member
      WHERE member.group_id = v_target_group.id
        AND member.contact_id = v_source_member.contact_id
      FOR UPDATE;

      INSERT INTO public.auto_account_contact_group_members AS existing_member (
$new$;
  v_old_copy text := $old$
      WHERE origin.membership_id = v_source_member.id AND origin.is_current = true
      ON CONFLICT DO NOTHING;

      INSERT INTO public.auto_account_contact_group_member_origins (
$old$;
  v_new_copy text := $new$
      WHERE origin.membership_id = v_source_member.id AND origin.is_current = true
      ON CONFLICT DO NOTHING;

      PERFORM public.aka_agent_sync_copied_data_group_origins(
        v_source_member.id,
        v_target_member.id,
        v_target_primary_before IS NULL
      );

      INSERT INTO public.auto_account_contact_group_member_origins (
$new$;
BEGIN
  IF v_signature IS NULL THEN
    RAISE EXCEPTION 'missing_data_group_move_writer';
  END IF;

  SELECT pg_catalog.pg_get_functiondef(v_signature)
  INTO v_definition;

  IF pg_catalog.strpos(v_definition, 'aka_agent_sync_copied_data_group_origins') > 0 THEN
    RETURN;
  END IF;
  IF (
    pg_catalog.length(v_definition)
    - pg_catalog.length(pg_catalog.replace(v_definition, v_old_declaration, ''))
  ) <> pg_catalog.length(v_old_declaration)
    OR (
      pg_catalog.length(v_definition)
      - pg_catalog.length(pg_catalog.replace(v_definition, v_old_upsert, ''))
    ) <> pg_catalog.length(v_old_upsert)
    OR (
      pg_catalog.length(v_definition)
      - pg_catalog.length(pg_catalog.replace(v_definition, v_old_copy, ''))
    ) <> pg_catalog.length(v_old_copy)
  THEN
    RAISE EXCEPTION 'unexpected_data_group_move_origin_shape';
  END IF;

  v_definition := pg_catalog.replace(
    v_definition, v_old_declaration, v_new_declaration
  );
  v_definition := pg_catalog.replace(
    v_definition, v_old_upsert, v_new_upsert
  );
  v_definition := pg_catalog.replace(
    v_definition, v_old_copy, v_new_copy
  );
  EXECUTE v_definition;
END;
$patch_move_primary_source$;

-- ---------------------------------------------------------------------------
-- 4. Append the stable source to both list-members RPC contracts.
-- ---------------------------------------------------------------------------

-- PostgreSQL cannot replace a function after changing TABLE OUT columns. The
-- authenticated wrapper depends on the implementation, so remove it first and
-- recreate both overloads with the same result contract.
DROP FUNCTION public.aka_agent_list_data_group_members(
  bigint, bigint, bigint, text, bigint[], boolean, text[], text[], text,
  bigint[], bigint[], bigint[], integer, integer, text, text
);
DROP FUNCTION public.aka_agent_list_data_group_members(
  bigint, bigint, bigint, text, bigint[], boolean, text[], text[], text,
  bigint[], bigint[], bigint[], integer, integer
);

CREATE FUNCTION public.aka_agent_list_data_group_members(
  p_staff_id bigint,
  p_organization_id bigint,
  p_group_id bigint,
  p_search text DEFAULT NULL,
  p_account_ids bigint[] DEFAULT NULL,
  p_include_accountless boolean DEFAULT true,
  p_contact_types text[] DEFAULT NULL,
  p_flatform_types text[] DEFAULT NULL,
  p_status text DEFAULT 'all',
  p_dataset_ids bigint[] DEFAULT NULL,
  p_ids bigint[] DEFAULT NULL,
  p_exclude_ids bigint[] DEFAULT NULL,
  p_offset integer DEFAULT 0,
  p_limit integer DEFAULT 100
)
RETURNS TABLE (
  id bigint,
  group_id bigint,
  contact_id bigint,
  name text,
  uid text,
  url text,
  phone text,
  email text,
  info1 text,
  info2 text,
  info3 text,
  info4 text,
  info5 text,
  contact_type text,
  flatform_type text,
  source_account_id bigint,
  source_account_name text,
  source_account_deleted boolean,
  dataset_ids bigint[],
  dataset_names text[],
  is_friend boolean,
  is_joined boolean,
  is_delete boolean,
  change_revision bigint,
  provenance jsonb,
  created_at timestamptz,
  updated_at timestamptz,
  primary_origin_id bigint,
  source_category_item_id bigint,
  source_code text,
  source_name text,
  source_automation_id bigint,
  source_automation_name text,
  total_count bigint
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  PERFORM public.aka_agent_internal_require_staff_tenant(
    p_staff_id, p_organization_id
  );
  IF COALESCE(p_status, 'all') NOT IN (
    'all', 'active', 'inactive', 'friend', 'stranger', 'joined', 'not_joined'
  )
    OR COALESCE(p_offset, 0) < 0
    OR COALESCE(p_limit, 100) NOT BETWEEN 1 AND 1000
  THEN
    RAISE EXCEPTION 'invalid_data_group_member_query';
  END IF;
  IF NOT EXISTS (
    SELECT 1
    FROM public.auto_account_contact_groups AS contact_group
    WHERE contact_group.id = p_group_id
      AND contact_group.staff_id = p_staff_id
      AND contact_group.organization_id = p_organization_id
      AND contact_group.purpose = 'data_group'
      AND contact_group.is_delete = false
  ) THEN
    RAISE EXCEPTION 'data_group_not_found';
  END IF;

  RETURN QUERY
  WITH filtered AS (
    SELECT
      member.id AS selected_member_id,
      member.group_id AS selected_group_id,
      member.contact_id,
      member.created_at AS member_created_at,
      member.updated_at AS member_updated_at,
      member.is_delete AS member_is_delete,
      member.change_revision,
      member.primary_origin_id,
      contact.name,
      contact.uid,
      contact.url,
      contact.phone,
      contact.email,
      contact.extra_data,
      contact.contact_type,
      contact.flatform_type,
      contact.account_id,
      contact.is_friend,
      contact.is_joined,
      account.name AS selected_account_name,
      COALESCE(account.is_delete, false) AS selected_account_deleted
    FROM public.auto_account_contact_group_members AS member
    JOIN public.auto_account_contacts AS contact
      ON contact.id = member.contact_id
    LEFT JOIN public.auto_accounts AS account
      ON account.id = contact.account_id
    WHERE member.group_id = p_group_id
      AND contact.staff_id = p_staff_id
      AND contact.organization_id = p_organization_id
      AND member.is_delete = false
      AND (
        COALESCE(p_status, 'all') = 'all'
        OR (
          COALESCE(p_status, 'all') = 'active' AND (
            (contact.contact_type = 'person' AND contact.is_friend = true)
            OR (contact.contact_type = 'group' AND contact.is_joined = true)
            OR contact.contact_type NOT IN ('person', 'group')
          )
        )
        OR (
          COALESCE(p_status, 'all') = 'inactive' AND (
            (contact.contact_type = 'person' AND contact.is_friend = false)
            OR (contact.contact_type = 'group' AND contact.is_joined = false)
          )
        )
        OR (
          COALESCE(p_status, 'all') = 'friend'
          AND contact.contact_type = 'person'
          AND contact.is_friend = true
        )
        OR (
          COALESCE(p_status, 'all') = 'stranger'
          AND contact.contact_type = 'person'
          AND contact.is_friend = false
        )
        OR (
          COALESCE(p_status, 'all') = 'joined'
          AND contact.contact_type = 'group'
          AND contact.is_joined = true
        )
        OR (
          COALESCE(p_status, 'all') = 'not_joined'
          AND contact.contact_type = 'group'
          AND contact.is_joined = false
        )
      )
      AND (
        NULLIF(btrim(COALESCE(p_search, '')), '') IS NULL
        OR contact.name ILIKE '%' || btrim(p_search) || '%'
        OR contact.uid ILIKE '%' || btrim(p_search) || '%'
        OR contact.phone ILIKE '%' || btrim(p_search) || '%'
        OR contact.email ILIKE '%' || btrim(p_search) || '%'
      )
      AND (
        p_account_ids IS NULL
        OR contact.account_id = ANY(p_account_ids)
        OR (
          COALESCE(p_include_accountless, true)
          AND contact.account_id IS NULL
        )
      )
      AND (
        COALESCE(p_include_accountless, true)
        OR contact.account_id IS NOT NULL
      )
      AND (
        p_contact_types IS NULL
        OR contact.contact_type = ANY(p_contact_types)
      )
      AND (
        p_flatform_types IS NULL
        OR contact.flatform_type = ANY(p_flatform_types)
      )
      AND (p_ids IS NULL OR member.id = ANY(p_ids))
      AND (
        p_exclude_ids IS NULL
        OR NOT (member.id = ANY(p_exclude_ids))
      )
      AND (
        p_dataset_ids IS NULL OR EXISTS (
          SELECT 1
          FROM public.auto_account_contact_group_member_origins AS dataset_origin
          WHERE dataset_origin.membership_id = member.id
            AND dataset_origin.dataset_id = ANY(p_dataset_ids)
            AND dataset_origin.is_current = true
        )
      )
  )
  SELECT
    filtered.selected_member_id,
    filtered.selected_group_id,
    filtered.contact_id,
    filtered.name,
    filtered.uid,
    filtered.url,
    filtered.phone,
    filtered.email,
    NULLIF(filtered.extra_data ->> 'info1', ''),
    NULLIF(filtered.extra_data ->> 'info2', ''),
    NULLIF(filtered.extra_data ->> 'info3', ''),
    NULLIF(filtered.extra_data ->> 'info4', ''),
    NULLIF(filtered.extra_data ->> 'info5', ''),
    filtered.contact_type,
    filtered.flatform_type,
    filtered.account_id::bigint,
    filtered.selected_account_name,
    filtered.selected_account_deleted,
    COALESCE((
      SELECT array_agg(current_dataset.id ORDER BY current_dataset.id)
      FROM (
        SELECT DISTINCT dataset.id, dataset.name
        FROM public.auto_account_contact_group_member_origins AS origin
        JOIN public.auto_account_contacts_dataset AS dataset
          ON dataset.id = origin.dataset_id
        WHERE origin.membership_id = filtered.selected_member_id
          AND origin.is_current = true
          AND dataset.is_delete = false
      ) AS current_dataset
    ), '{}'::bigint[]),
    COALESCE((
      SELECT array_agg(current_dataset.name ORDER BY current_dataset.id)
      FROM (
        SELECT DISTINCT dataset.id, dataset.name
        FROM public.auto_account_contact_group_member_origins AS origin
        JOIN public.auto_account_contacts_dataset AS dataset
          ON dataset.id = origin.dataset_id
        WHERE origin.membership_id = filtered.selected_member_id
          AND origin.is_current = true
          AND dataset.is_delete = false
      ) AS current_dataset
    ), '{}'::text[]),
    filtered.is_friend,
    filtered.is_joined,
    filtered.member_is_delete,
    filtered.change_revision,
    COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'id', origin.id,
        'membership_id', origin.membership_id,
        'kind', origin.kind,
        'relationship_kind', origin.relationship_kind,
        'dataset_id', origin.dataset_id,
        'batch_id', origin.batch_id,
        'source_account_id', origin.source_account_id,
        'source_account_name', source_account.name,
        'source_account_deleted', COALESCE(source_account.is_delete, false),
        'automation_detail_id', origin.automation_detail_id,
        'automation_id', automation_detail.automation_id,
        'automation_name', automation.name,
        'automation_detail_status', automation_detail.status,
        'source_campaign_id', automation_detail.source_campaign_id,
        'source_campaign_name', source_campaign.name,
        'target_campaign_id', automation_detail.target_campaign_id,
        'target_campaign_name', target_campaign.name,
        'source_name_snapshot', origin.source_name_snapshot,
        'is_current', origin.is_current,
        'created_at', origin.created_at,
        'updated_at', origin.updated_at
      ) ORDER BY origin.created_at, origin.id)
      FROM public.auto_account_contact_group_member_origins AS origin
      LEFT JOIN public.auto_accounts AS source_account
        ON source_account.id = origin.source_account_id
      LEFT JOIN public.auto_automation_detail AS automation_detail
        ON automation_detail.id = origin.automation_detail_id
      LEFT JOIN public.auto_automation AS automation
        ON automation.id = automation_detail.automation_id
      LEFT JOIN public.auto_campaigns AS source_campaign
        ON source_campaign.id = automation_detail.source_campaign_id
      LEFT JOIN public.auto_campaigns AS target_campaign
        ON target_campaign.id = automation_detail.target_campaign_id
      WHERE origin.membership_id = filtered.selected_member_id
    ), '[]'::jsonb),
    filtered.member_created_at,
    filtered.member_updated_at,
    primary_source.primary_origin_id,
    primary_source.source_category_item_id,
    primary_source.source_code,
    primary_source.source_name,
    primary_source.source_automation_id,
    primary_source.source_automation_name,
    count(*) OVER ()::bigint
  FROM filtered
  LEFT JOIN LATERAL (
    SELECT
      primary_origin.id AS primary_origin_id,
      category_item.id AS source_category_item_id,
      category_item.code AS source_code,
      category_item.name AS source_name,
      automation.id AS source_automation_id,
      CASE WHEN category_item.code = 'automation' THEN COALESCE(
        NULLIF(btrim(automation.name), ''),
        NULLIF(btrim(primary_origin.source_name_snapshot), '')
      ) END AS source_automation_name
    FROM public.auto_account_contact_group_member_origins AS primary_origin
    JOIN public.category_item AS category_item
      ON category_item.id = primary_origin.source_category_item_id
     AND category_item.is_active = true
     AND category_item.managed_by = 'system'
     AND category_item.code =
       public.aka_agent_data_group_source_code(primary_origin.kind)
    JOIN public.category_type AS category_type
      ON category_type.id = category_item.category_type_id
     AND category_type.namespace = 'common'
     AND category_type.code = 'data_source'
     AND category_type.managed_by = 'system'
     AND category_type.is_active = true
    LEFT JOIN public.auto_automation_detail AS automation_detail
      ON automation_detail.id = primary_origin.automation_detail_id
     AND automation_detail.staff_id = p_staff_id
     AND automation_detail.organization_id = p_organization_id
    LEFT JOIN public.auto_automation AS automation
      ON automation.id = automation_detail.automation_id
     AND automation.staff_id = p_staff_id
     AND automation.organization_id = p_organization_id
    WHERE primary_origin.id = filtered.primary_origin_id
      AND primary_origin.membership_id = filtered.selected_member_id
      AND primary_origin.is_current = true
    LIMIT 1
  ) AS primary_source ON true
  ORDER BY filtered.member_created_at DESC, filtered.selected_member_id DESC
  OFFSET COALESCE(p_offset, 0)
  LIMIT COALESCE(p_limit, 100);
END;
$$;

CREATE FUNCTION public.aka_agent_list_data_group_members(
  p_staff_id bigint,
  p_organization_id bigint,
  p_group_id bigint,
  p_search text,
  p_account_ids bigint[],
  p_include_accountless boolean,
  p_contact_types text[],
  p_flatform_types text[],
  p_status text,
  p_dataset_ids bigint[],
  p_ids bigint[],
  p_exclude_ids bigint[],
  p_offset integer,
  p_limit integer,
  p_auth_username text,
  p_auth_password text
)
RETURNS TABLE (
  id bigint,
  group_id bigint,
  contact_id bigint,
  name text,
  uid text,
  url text,
  phone text,
  email text,
  info1 text,
  info2 text,
  info3 text,
  info4 text,
  info5 text,
  contact_type text,
  flatform_type text,
  source_account_id bigint,
  source_account_name text,
  source_account_deleted boolean,
  dataset_ids bigint[],
  dataset_names text[],
  is_friend boolean,
  is_joined boolean,
  is_delete boolean,
  change_revision bigint,
  provenance jsonb,
  created_at timestamptz,
  updated_at timestamptz,
  primary_origin_id bigint,
  source_category_item_id bigint,
  source_code text,
  source_name text,
  source_automation_id bigint,
  source_automation_name text,
  total_count bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT public.auto_assert_automation_identity(
    p_staff_id,
    p_organization_id,
    p_auth_username,
    p_auth_password
  );
  SELECT *
  FROM public.aka_agent_list_data_group_members(
    p_staff_id,
    p_organization_id,
    p_group_id,
    p_search,
    p_account_ids,
    p_include_accountless,
    p_contact_types,
    p_flatform_types,
    p_status,
    p_dataset_ids,
    p_ids,
    p_exclude_ids,
    p_offset,
    p_limit
  );
$$;

COMMENT ON TABLE public.category_type IS
  'Cross-project category namespaces and type definitions.';
COMMENT ON TABLE public.category_item IS
  'Cross-project values belonging to a category type.';
COMMENT ON COLUMN public.auto_account_contact_group_member_origins.source_category_item_id IS
  'Shared common/data_source category mapped from this precise origin kind; NULL means deliberately unmapped.';
COMMENT ON COLUMN public.auto_account_contact_group_members.primary_origin_id IS
  'Sticky current mapped origin displayed as the Data Group member source.';
COMMENT ON FUNCTION public.aka_agent_list_data_group_members(
  bigint, bigint, bigint, text, bigint[], boolean, text[], text[], text,
  bigint[], bigint[], bigint[], integer, integer
) IS
  'Lists paged Data Group memberships with stable primary source category and automation identity.';

-- ---------------------------------------------------------------------------
-- 5. Catalog/RPC security and internal helper ACLs.
-- ---------------------------------------------------------------------------

ALTER TABLE public.category_type ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.category_item ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS category_type_read_catalog ON public.category_type;
CREATE POLICY category_type_read_catalog
  ON public.category_type
  FOR SELECT
  TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS category_item_read_catalog ON public.category_item;
CREATE POLICY category_item_read_catalog
  ON public.category_item
  FOR SELECT
  TO anon, authenticated
  USING (true);

REVOKE ALL PRIVILEGES ON TABLE public.category_type
  FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.category_item
  FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.category_type
  TO anon, authenticated;
GRANT SELECT ON TABLE public.category_item
  TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.category_type
  TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.category_item
  TO service_role;

REVOKE ALL PRIVILEGES ON SEQUENCE public.category_type_id_seq
  FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.category_item_id_seq
  FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SEQUENCE public.category_type_id_seq
  TO service_role;
GRANT USAGE ON SEQUENCE public.category_item_id_seq
  TO service_role;

REVOKE ALL ON FUNCTION public.touch_category_catalog_updated_at()
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.aka_agent_data_group_source_code(text)
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.aka_agent_data_group_source_category_item_id(text)
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.aka_agent_sync_data_group_member_primary_origin(
  bigint, bigint, boolean
) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.aka_agent_stamp_data_group_source_category()
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.aka_agent_refresh_data_group_primary_from_origin()
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.aka_agent_repair_data_group_primary_from_origin()
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.aka_agent_guard_data_group_member_primary_origin()
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.aka_agent_refresh_data_group_primary_from_member()
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.aka_agent_refresh_data_group_primary_from_category_item()
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.aka_agent_refresh_data_group_primary_from_category_type()
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.aka_agent_sync_copied_data_group_origins(
  bigint, bigint, boolean
) FROM PUBLIC, anon, authenticated, service_role;

REVOKE ALL ON FUNCTION public.aka_agent_list_data_group_members(
  bigint, bigint, bigint, text, bigint[], boolean, text[], text[], text,
  bigint[], bigint[], bigint[], integer, integer
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.aka_agent_list_data_group_members(
  bigint, bigint, bigint, text, bigint[], boolean, text[], text[], text,
  bigint[], bigint[], bigint[], integer, integer
) TO service_role;

REVOKE ALL ON FUNCTION public.aka_agent_list_data_group_members(
  bigint, bigint, bigint, text, bigint[], boolean, text[], text[], text,
  bigint[], bigint[], bigint[], integer, integer, text, text
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.aka_agent_list_data_group_members(
  bigint, bigint, bigint, text, bigint[], boolean, text[], text[], text,
  bigint[], bigint[], bigint[], integer, integer, text, text
) TO anon, authenticated, service_role;

NOTIFY pgrst, 'reload schema';

COMMIT;
