-- Internal akaBiz contact tags. Tag catalog is staff-scoped; contact
-- membership is stored directly on auto_account_contacts.akabiz_tag_ids.

CREATE TABLE IF NOT EXISTS public.auto_contact_tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  is_delete boolean NOT NULL DEFAULT false,
  staff_id bigint NOT NULL REFERENCES public.org_staff(id) ON DELETE CASCADE,
  organization_id bigint REFERENCES public.org_organization(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_auto_contact_tags_active_staff_name
  ON public.auto_contact_tags (staff_id, lower(name))
  WHERE is_delete = false;

CREATE INDEX IF NOT EXISTS idx_auto_contact_tags_staff
  ON public.auto_contact_tags (staff_id, is_delete, updated_at DESC);

ALTER TABLE public.auto_account_contacts
  ADD COLUMN IF NOT EXISTS akabiz_tag_ids bigint[] NOT NULL DEFAULT '{}'::bigint[];

CREATE INDEX IF NOT EXISTS idx_auto_account_contacts_akabiz_tag_ids
  ON public.auto_account_contacts USING gin (akabiz_tag_ids);

COMMENT ON TABLE public.auto_contact_tags IS
  'Staff-scoped internal akaBiz contact tag catalog.';

COMMENT ON COLUMN public.auto_account_contacts.akabiz_tag_ids IS
  'Internal akaBiz tag IDs attached directly to this contact. Tag names live in auto_contact_tags.';
