-- Staff-scoped media groups for quick campaign media selection.

BEGIN;

CREATE TABLE IF NOT EXISTS public.auto_media_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  is_delete boolean NOT NULL DEFAULT false,
  staff_id bigint NOT NULL REFERENCES public.org_staff(id) ON DELETE CASCADE,
  organization_id bigint REFERENCES public.org_organization(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_auto_media_groups_staff_name_active
  ON public.auto_media_groups (staff_id, lower(name))
  WHERE is_delete = false;

CREATE INDEX IF NOT EXISTS idx_auto_media_groups_staff
  ON public.auto_media_groups (staff_id, is_delete, created_at DESC);

CREATE TABLE IF NOT EXISTS public.auto_media_group_items (
  group_id bigint NOT NULL REFERENCES public.auto_media_groups(id) ON DELETE CASCADE,
  media_file_id bigint NOT NULL REFERENCES public.auto_media_files(id) ON DELETE CASCADE,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (group_id, media_file_id)
);

CREATE INDEX IF NOT EXISTS idx_auto_media_group_items_group
  ON public.auto_media_group_items (group_id, sort_order, created_at);

CREATE INDEX IF NOT EXISTS idx_auto_media_group_items_media_file
  ON public.auto_media_group_items (media_file_id);

COMMENT ON TABLE public.auto_media_groups IS
  'Staff-scoped media groups used as quick selectors for campaign media snapshots.';

COMMENT ON TABLE public.auto_media_group_items IS
  'Many-to-many membership between media groups and uploaded media files.';

NOTIFY pgrst, 'reload schema';

COMMIT;
