BEGIN;
SET LOCAL lock_timeout='3s';
SET LOCAL statement_timeout='15s';
LOCK TABLE public.auto_error IN SHARE ROW EXCLUSIVE MODE;
DO $preflight$ BEGIN
 IF EXISTS(SELECT 1 FROM supabase_migrations.schema_migrations WHERE name ~ '^migration_v370(_|$)') THEN RAISE EXCEPTION 'v370: version already used'; END IF;
 IF (SELECT md5(string_agg(to_jsonb(e)::text,'|' ORDER BY id)) FROM public.auto_error e)<>'3f53554bba52af2e48b1f395b11103c4' THEN RAISE EXCEPTION 'v370: policy table changed since backup'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.auto_error e WHERE id=81 AND error_code='err_fb_add_friend_unavailable' AND md5(to_jsonb(e)::text)='1173220a341d33b89d5cbb2730f27beb') THEN RAISE EXCEPTION 'v370: target policy changed'; END IF;
END $preflight$;
UPDATE public.auto_error SET noti_running_process='Không thể gửi lời mời kết bạn, nút kết bạn bị ẩn',noti_campaign='Không thể gửi lời mời kết bạn, nút kết bạn bị ẩn' WHERE id=81 AND error_code='err_fb_add_friend_unavailable';
DO $postflight$ BEGIN
 IF (SELECT to_jsonb(e) FROM public.auto_error e WHERE id=81) IS DISTINCT FROM '{"count_consecutive_errors":null,"counts_toward_bad_target":false,"counts_toward_limit":false,"created_at":"2026-10-06T03:37:29.593089+00:00","detail_mode":null,"detail_status":"thất bại","detail_status_id":null,"disable_action_codes":[],"disable_action_days":null,"disable_action_mode":"fixed_minutes","disable_action_time":null,"error_code":"err_fb_add_friend_unavailable","error_desc":"Phạm vi: Không có nút kết bạn, đã loại trừ trạng thái đã là bạn/đã gửi lời mời.\n\nGiới hạn cấu hình / cần triển khai sau: Không tạo policy lỗi cho đã là bạn/đã gửi lời mời. Chỉ suy ra chặn tài khoản khi có bằng chứng; không khóa chỉ vì một hồ sơ thiếu nút.\n\nv346 chỉ bổ sung danh mục DB. Nhận diện mã và hành vi chưa được tích hợp vào runtime; is_active=true không tự nhận diện lỗi mới.\n\nNguồn: Danh_sach_loi_Facebook_auto_28092026.xlsx / Danh sách lỗi FB / dòng 13\n\nNguồn: FACEBOOK_ERROR_HANDLING_20260928.xlsx / 1. Danh sách lỗi FB / dòng 18","error_element":null,"error_name":"Không thể gửi lời mời kết bạn Facebook","error_type":"external facebook","id":81,"input_effect":null,"is_active":true,"is_delete":false,"noti_campaign":"Không thể gửi lời mời kết bạn, nút kết bạn bị ẩn","noti_running_process":"Không thể gửi lời mời kết bạn, nút kết bạn bị ẩn","time_disable_actions":null,"update_login_status":null,"update_status_account":null,"update_status_campaign":null,"updated_at":"2026-10-06T03:37:29.593089+00:00","zalo_action_codes":[],"zalo_error_codes":[]}'::jsonb THEN RAISE EXCEPTION 'v370: unexpected target change'; END IF;
 IF (SELECT md5(string_agg(to_jsonb(e)::text,'|' ORDER BY id)) FROM public.auto_error e WHERE id<>81)<>'4a0ef69098872031653fe90596790ae7' THEN RAISE EXCEPTION 'v370: another policy changed'; END IF;
END $postflight$;
DO $guard$ BEGIN
 IF (SELECT to_jsonb(e) FROM public.auto_error e WHERE id=81) IS DISTINCT FROM '{"count_consecutive_errors":null,"counts_toward_bad_target":false,"counts_toward_limit":false,"created_at":"2026-10-06T03:37:29.593089+00:00","detail_mode":null,"detail_status":"thất bại","detail_status_id":null,"disable_action_codes":[],"disable_action_days":null,"disable_action_mode":"fixed_minutes","disable_action_time":null,"error_code":"err_fb_add_friend_unavailable","error_desc":"Phạm vi: Không có nút kết bạn, đã loại trừ trạng thái đã là bạn/đã gửi lời mời.\n\nGiới hạn cấu hình / cần triển khai sau: Không tạo policy lỗi cho đã là bạn/đã gửi lời mời. Chỉ suy ra chặn tài khoản khi có bằng chứng; không khóa chỉ vì một hồ sơ thiếu nút.\n\nv346 chỉ bổ sung danh mục DB. Nhận diện mã và hành vi chưa được tích hợp vào runtime; is_active=true không tự nhận diện lỗi mới.\n\nNguồn: Danh_sach_loi_Facebook_auto_28092026.xlsx / Danh sách lỗi FB / dòng 13\n\nNguồn: FACEBOOK_ERROR_HANDLING_20260928.xlsx / 1. Danh sách lỗi FB / dòng 18","error_element":null,"error_name":"Không thể gửi lời mời kết bạn Facebook","error_type":"external facebook","id":81,"input_effect":null,"is_active":true,"is_delete":false,"noti_campaign":"Không thể gửi lời mời kết bạn, nút kết bạn bị ẩn","noti_running_process":"Không thể gửi lời mời kết bạn, nút kết bạn bị ẩn","time_disable_actions":null,"update_login_status":null,"update_status_account":null,"update_status_campaign":null,"updated_at":"2026-10-06T03:37:29.593089+00:00","zalo_action_codes":[],"zalo_error_codes":[]}'::jsonb THEN RAISE EXCEPTION 'v370 rollback: policy changed; reconcile first'; END IF;
END $guard$;
UPDATE public.auto_error SET noti_running_process='Không thể gửi lời mời kết bạn Facebook',noti_campaign='Không thể gửi lời mời kết bạn Facebook' WHERE id=81 AND error_code='err_fb_add_friend_unavailable';
DO $roundtrip$ BEGIN IF (SELECT md5(string_agg(to_jsonb(e)::text,'|' ORDER BY id)) FROM public.auto_error e)<>'3f53554bba52af2e48b1f395b11103c4' THEN RAISE EXCEPTION 'v370 smoke: rollback differs'; END IF; END $roundtrip$;
ROLLBACK;
SELECT 'passed: both notifications updated, other values unchanged, rollback restores entire table' AS result;
